CloudHealth/amazon-pricing

README.md
All except the Solano CI badge, partly because of #62, partly because it is not a "[shields.io](http://shields.io/)-style" badge.
=> Use SVG badges in the README instead of the PNG ones

lib/amazon-pricing/definitions/instance-type.rb
EBS-only instances are being commented out, as well as other types that CloudWatch does not pick up.
These values come from an (internal) analysis made at: https://docs.google.com/spreadsheets/d/17Hg4z8abYKOz0WXNEDZKLPUlVKKKedfPWkz0YieKGwI
=> Add disk metrics capacities (bytes per second and ops per second)

Gemfile.lock, lib/amazon-pricing/version.rb
The Gemfile.lock changes were obtained by running `bundle install`.
=> Bump gem version and remove entries in Gemfile.lock

Gemfile.lock, lib/amazon-pricing/definitions/rds-instance-type.rb, lib/amazon-pricing/rds-price-list.rb, lib/amazon-pricing/version.rb
There was missing AWS js URLs which were missing for RDS instances:  this now includes them.
=> update to use most-recent aws URLs

Gemfile.lock, lib/amazon-pricing/definitions/instance-type.rb, lib/amazon-pricing/version.rb
For example, calling `disk_bytes_per_sec_capacity('t1.micro')` would raise a `StandardError`.
=> Make sure capacity helpers do not raise an Error when there are no capacities for a given type

Gemfile.lock, lib/amazon-pricing/helpers/instance-type.rb, lib/amazon-pricing/version.rb, spec/lib/amazon-pricing/helpers/instance-type-spec.rb
Add missing instance types to classification data structure, and add a test to make sure all instance types we know about are represented
=> Fix rollbar "No instance family members for rightsizing."

Gemfile.lock, lib/amazon-pricing/definitions/database-type.rb, lib/amazon-pricing/definitions/rds-instance-type.rb, lib/amazon-pricing/rds-price-list.rb, lib/amazon-pricing/version.rb, test/ec2_instance_types_test.rb
**Description:**
Changes encompass the following:
- oracle-se2 (License Included) pricings were missing
- reordered enumeration of oracle instances, so permutations are more clear
- since oracle BYOL is the same for all types (as described by AWS), we now explicitly copy all byol
- minor change to sqlserver_web (includes multi-AZ), and, aurora (includes single-AZ).
Operationally, the result shows that oracle-se1 and oracle-se2 now yields the same number of prices;  and oracle-se/ee yields half that number (since they only have BYOL prices).
**Review:**
=> missing prices: oracle-se2 and byol; some aurora

CHANGELOG.md, Gemfile.lock, lib/amazon-pricing/definitions/instance-type.rb, lib/amazon-pricing/version.rb
Below is the result of:
```rb
> AwsPricing::InstanceType.populate_lookups
=> ["http://a0.awsstatic.com/pricing/1/ec2/linux-od.min.js", "http://a0.awsstatic.com/pricing/1/ec2/previous-generation/linux-od.min.js"]
> AwsPricing::InstanceType.class_variable_get(:@@Compute_Units_Lookup)
```
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td>
<pre>{
"t2.nano" => 0,
"t2.micro" => 0,
"t2.small" => 0,
"t2.medium" => 0,
"t2.large" => 0,
"m4.large" => 6,
"m4.xlarge" => 13,
"m4.2xlarge" => 26,
"m4.4xlarge" => 53,
"m4.10xlarge" => 124,
"m3.medium" => 3,
"m3.large" => 6,
"m3.xlarge" => 13,
"m3.2xlarge" => 26,
"c4.large" => 8,
"c4.xlarge" => 16,
"c4.2xlarge" => 31,
"c4.4xlarge" => 62,
"c4.8xlarge" => 132,
"c3.large" => 7,
"c3.xlarge" => 14,
"c3.2xlarge" => 28,
"c3.4xlarge" => 55,
"c3.8xlarge" => …
=> Fetch ECUs as floats instead of integers

lib/amazon-pricing/helpers/instance-type.rb, lib/amazon-pricing/version.rb
fixing typo
Rollbar: #45172 CloudHealth::RightsizingJobError: Computing aws:ec2:instance scores for asset_id 2542620950959 failed: undefined method `index' for nil:NilClass
=> [ENG-4072]  fixes typo of i4 instance type that caused a rollbar

lib/amazon-pricing/definitions/ec2-instance-type.rb, lib/amazon-pricing/definitions/instance-type.rb, lib/amazon-pricing/version.rb
this blocks pricing-update since it (now) shows as an unsupported type:  this adds in enough so it's a supported type.
=> [ENG-9515] add cache.r4 support

lib/amazon-pricing/definitions/ec2-instance-type.rb, lib/amazon-pricing/definitions/instance-type.rb, lib/amazon-pricing/ec2-dhi-price-list.rb, lib/amazon-pricing/ec2-di-price-list.rb, lib/amazon-pricing/helpers/instance-type.rb, lib/amazon-pricing/version.rb
This adds the 'basic' i3.metal support.
Due to the (lack of) clarity around SF for this, and the pervasive uses of the SIZE_TO_NF_TABLE hash clients, this change is initially/temporarily hard-coding the `metal` size as a fixed NF of 128 (this would only work for the i3 family).  The proposed new NF API (using api_name_to_nf) is also included here to ease the transition to handle `metal`.
The i3.metal is inherently _both_ Dedicated, and, Dedicated-Host.  This led to discovering a bug where we were not incorporating the previously-new linuxsql OS types, so that change is incorporated into this fix (to also support the i3 dedicated cases).
=> [AWS-2539] adding i3.metal, fixes for linuxsql DH and DI

lib/amazon-pricing/definitions/ec2-instance-type.rb, lib/amazon-pricing/definitions/instance-type.rb, lib/amazon-pricing/ec2-dhi-price-list.rb, lib/amazon-pricing/version.rb
adding m5d family:  https://aws.amazon.com/blogs/aws/ec2-instance-update-m5-instances-with-local-nvme-storage-m5d/
announced: 2018-06-04
=> [AWS-2541] adding m5d family

lib/amazon-pricing/ec2-price-list.rb, lib/amazon-pricing/version.rb
Missed capture (static js) pricing files for previousGen instance types.
=> [AWS-2720] adds missing linuxSQL variants for previousGen

lib/amazon-pricing/version.rb
missed version file, so can't publish gem (for neptune add)
=> [AWS-2540] missed version bump to 116, for neptune

lib/amazon-pricing/definitions/ec2-instance-type.rb, lib/amazon-pricing/version.rb
Here's [How to do a Code Review](https://cloudhealthtech.atlassian.net/wiki/spaces/EN/pages/17989636/Code+Review)
- JIRA Ticket(s):https://cloudhealthtech.atlassian.net/browse/AWS-3284
- Design Doc (where applicable):
- Link to passing Solano build (if PR tests are failing due to inter-repo dependencies):
- Create new process, run by rake task, to automatically populate aws_instance_type_profiles if a new instance type is added
-*NOTE* This PR right now does *NOT* include code to allow updates of existing instance profiles if what we have in the table does not match the api. This will be a feature that will be added.
_Rollback Plan:_
-Revert
=> AWS-3584: adding in support to allow us to automatically populate instance profiles

lib/amazon-pricing/helpers/instance-type.rb, lib/amazon-pricing/version.rb
Jira Ticket: https://cloudhealthtech.atlassian.net/browse/ENG-15303
Moved previous declaration of VPC_ONLY_INSTANCE_FAMILIES out of other repository, where it was declared multiple times, to amazon-pricing. Should help speed up additions of new instance families, as we will have less code we have to update.
=> Moving VPC only instance family array to be in amazon-pricing

Jenkinsfile
This PR fixes the syntax of the cron trigger scheduling so the master branch kicks off on a weekly interval.
=> [QUAL-976] Fix the scheduled pipeline trigger in Jenkins

lib/amazon-pricing/helpers/instance-type.rb, lib/amazon-pricing/version.rb
Updating all methods in instance-type to be class methods, rather than instance-methods, so api_name_to_nf can be used by other classes/modules outside of amazon-pricing.
Moving 'm3' into the previous generation instances, as it is no longer a current instance family
=> Updating methods to allow us to access new api_name_to_nf method

lib/amazon-pricing/helpers/instance-type.rb, lib/amazon-pricing/version.rb, spec/lib/amazon-pricing/helpers/instance-type-spec.rb
I have a PR to switch a few usages of `SIZE_TO_NF_TABLE` in cht_billing to use this method, but I need it to support looking up normalization factor for `xl` instance types first.
For example `4xl` -> `4xlarge`
This uses a regex sub out any instance types ending in `xl` to end in `xlarge`
cht_billing PR: https://github.com/CloudHealth/cht_billing/pull/1396
=> [ENG-16791] Substitute xl instance types for xlarge

lib/amazon-pricing/definitions/ec2-instance-type.rb, lib/amazon-pricing/version.rb
Adding a network capacity description mapping
Current state:
After change:
=> [AWS-4393] Adding network capacity mapping
